### ISSUE TITLE
Can you support page layout?

### ISSUE THREAD

**Issue by esraerik** [ckeditor/ckeditor5-editor-inline#17]
Hi,
I'm studying about page layout like A3, A4, A5 in CKEditor 4. In CKEditor 4 this feature is hard to develop. Because I want to use CKEditor default A4 page layout. But I can add something to text page only with click a toolbar button . If you support this feature, can I access it in this repo?

Or If ask my question properly – can you support default page layout like A4 or can I add this property in this source quickly?

**Comment by oleq** [comment]
Hi, @esraerik! Because this topic touches all editor implementations, take a look at my [response](https://github.com/ckeditor/ckeditor5-design/issues/147#issuecomment-299422026) to your questions in the design repository. I hope it will help you understand our position limitations.
