### ISSUE TITLE
The position of the floating toolbar is not updated after the editable grew

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-editor-inline#4]
![mar-09-2017 11-18-51](https://cloud.githubusercontent.com/assets/156149/23745925/61e80bf8-04ba-11e7-8e7c-1633a6d681ce.gif)

**Comment by oleq** [comment]
https://github.com/ckeditor/ckeditor5-ui/issues/170 will help with this issue a lot.
